### ISSUE TITLE
Grid size smaller than 1

### ISSUE THREAD

**Issue by nvoelzow** [unitycoder/UnityPointCloudViewer#101]
When using the PointCloudConverter to convert an LAS file to v3, is it somehow possible to use grid sizes smaller than 1 to reduce the size of the individual output tiles when working for example with high resolution indoor scans?

Trying to set it for example to 0.5 through command line args I get:
0> Invalid gridsize parameter: 0.5

The UI version just quietly ignores this and doesn't start converting

Is this just a limitation by the parameter sanity check or does the format not support smaller tile sizes?

**Comment by unitycoder** [comment]
its limited right now in here:
https://github.com/unitycoder/PointCloudConverter/blob/master/Tools/ArgParser.cs#L346

but on a quick test it does seem to work with 0.5 and smaller values. (cant remember right now what was the original issue why it was limited, but ill remove the limitation).

**Comment by nvoelzow** [comment]
Ah perfect - thank you very much!

**Comment by unitycoder** [comment]
new build allows up to 0.01 *but should note that values below 1 are not really tested..
https://github.com/unitycoder/UnityPointCloudViewer/wiki/Commandline-Tools

**Comment by unitycoder** [comment]
out now in v2.60
