### ISSUE TITLE
swap=false by default in CLI

### ISSUE THREAD

**Issue by nvoelzow** [unitycoder/UnityPointCloudViewer#102]
On PointCloudConverter command line, adding swap=false creates the same output as omitting the parameter - only adding swap=true creates a diffferent output

**Comment by unitycoder** [comment]
swap is enabled by default,
so what should happen is:
- swap not given: swap = true
- swap set to false: swap = false
- swap set to true: swap = true

*this is probably already fixed, can report to https://github.com/unitycoder/PointCloudConverter if still happening.
