### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by nvoelzow** [unitycoder/UnityPointCloudViewer#110]
Every now and then when trying to load large portions of high resolution point clouds I will get this error when using the (original) PointCloudViewerTilesDX11 :

NullReferenceException: Object reference not set to an instance of an object
UnityLibrary.MainThread+<Executer>d__12.MoveNext () (at Assets/PointCloudTools/PointCloudViewerDX11/Scripts/Common/MainThread.cs:74)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <d29d557b212f474390dc0b17ef6ce0dd>:0)

after this happens no more tiles will be loaded until I restart the Component.

Unfortunately it only happens from time to time, so it's not exactly easy to track down...

**Comment by unitycoder** [comment]
ok adding to things to check list, i remember seeing this few times, but thought that it was fixed by those while-loops after CallInitBuffers line, to make sure they are ready.

**Comment by Yangfb91** [comment]
same issue, The only way is Restart my app.

**Comment by unitycoder** [comment]
aha, need to check more.. which unity version, and do you have [x] use native arrays, and [x] release tile memory enabled? (just wondering if its related to those)

**Comment by Yangfb91** [comment]
![image](https://user-images.githubusercontent.com/50657481/195520350-3506c295-94de-48c9-9758-b25b9fffdae5.png)

**Comment by unitycoder** [comment]
ok, does it happen mostly in the build, less in editor?

**Comment by unitycoder** [comment]
one thing that you can test (*or email me, so i'll send updated test script)
- open PointCloudViewerTilesDX11.cs
- Find IEnumerator InitDX11BufferA() and IEnumerator InitDX11BufferB()
- Add try-catches inside that method (except cannot add lines with ".. yield return 0;" inside those try catch, so 3 separate try catches, to catch them all! 
- Then run build, if error happens, its most likely in those parts, and might get more info in player.log (or in editor, if happens there)

example, inside InitDX11BufferA()
1st trycatch:
![image](https://user-images.githubusercontent.com/5438317/195570892-fa4d3302-ffc0-4299-9846-bfbd9145ea92.png)

2nd
![image](https://user-images.githubusercontent.com/5438317/195571016-1d0ad533-7c56-4ff9-aa4a-9495c2c42abb.png)

3rd
![image](https://user-images.githubusercontent.com/5438317/195571117-6a95489a-d56a-4831-8392-9d5d04e637d7.png)

**Comment by Yangfb91** [comment]
I test my proj mostly in editor,so i am not sure which one happens a lot.
And i will test  try-catches to get more info.

**Comment by unitycoder** [comment]
MainThread code has had updates, more in v2.80, should help with some null ref issues.
