### ISSUE TITLE
Bringing frames from Ouster pcap into animated point cloud

### ISSUE THREAD

**Issue by bjornsyse** [unitycoder/UnityPointCloudViewer#128]
Hi,

I'm curious if I could try the animated point cloud feature with some frames recorded off my ouster OS0. From ouster studio I can export all frames as CSV format, 

![image](https://user-images.githubusercontent.com/26255606/149927459-1c374e78-dcda-4bf8-81e2-c915a0d52e15.png)

Header:

```
"Point:0","Point:1","Point:2","Signal Photons","Reflectivity","Channel","Ambiant Photons","Range","Raw Timestamp"
3.300625562667847,0.6534615755081177,3.262648344039917,10.0,1.0,0.0,136.0,4695.0,241115224980.0
```

But reading this (https://github.com/unitycoder/UnityPointCloudViewer/wiki/Converting-.PLY-Frames-to-Animated-Point-Cloud-.bin) I see the converter expects PLY files. Any tips for a conversion there between? 

Regards Björn

**Comment by unitycoder** [comment]
if you can email me one or few csv files i'll check.

**Comment by unitycoder** [comment]
closing this here, ouster viewer should help, once its out
https://forum.unity.com/threads/unity-ouster-lidar-viewer-plugin-wip.1345199/

or need to create small converter for CSV > PLY, to use that ply converter.
