### ISSUE TITLE
how to import las/laz files

### ISSUE THREAD

**Issue by steffnorbert** [unitycoder/UnityPointCloudViewer#132]
Can someone guide me to import a .las or .laz file into Unity. I've bought and downloaded the Pointcloud Viewer and Tools extension imported the package, but can't seem to find a way to import the pointcloud. 
Note: I'm more used to autodesk and GIS softwares.

**Comment by unitycoder** [comment]
Added 3 sample videos for LAS conversion:
LAS to V1 (legacy format) : https://www.youtube.com/watch?v=O80zDO4g15g
LAS to V2 (single file faster) : https://www.youtube.com/watch?v=DmyIY61ThvE
LAS to V3 (tiled format) : https://www.youtube.com/watch?v=nVFSFTyQhp8

Notes:
- LAS files can be converted inside editor, into V1 binary format (which is fine for smaller clouds). If need faster loading or larger clouds, need to use external converter from https://github.com/unitycoder/PointCloudConverter/releases (it can be used from command line or as standalone, in the videos i use it as standalone (GUI)).

**Comment by steffnorbert** [comment]
[image: image.png]
Thank you so much for your e-mail, I managed to import my pointcloud, but
somehow not only the RGB points get imported, but another set of points
also. As you can see in the image attached the blue points. Can you help me
get rid of those points? Is there a workflow to not import those or to
delete them?

Thanks in advance,

**Comment by unitycoder** [comment]
@steffnorbert can you send image in email (my email is in the documentation pdf) *you replied to github message, so it didn't include attachments. (and these are public messages)

**Comment by steffnorbert** [comment]
![image](https://user-images.githubusercontent.com/102899074/184858388-9846312b-8c08-468f-aea2-2b7916b85b5d.png)
<img width="960" alt="Pointcloud" src="https://user-images.githubusercontent.com/102899074/184858565-096a3ff7-c293-4a30-9e16-e9fd80f3220f.png">

I uploaded it here. can't seem to find your e-mail.

**Comment by unitycoder** [comment]
ok that looks strange,

if you can email your source las file? (one possibility is that las file contains extra data)
![image](https://user-images.githubusercontent.com/5438317/184884807-0e4c0622-d526-48d2-bc05-508c77ea5d42.png)

or if you want to test, open your source file in CloudCompare,
then export as LAS/LAZ (1.4)

**Comment by unitycoder** [comment]
ok heres the issue, https://github.com/unitycoder/UnityPointCloudViewer/issues/133

closing this one, can follow up on that 133 issue, if need to use the inside editor converter.
