### ISSUE TITLE
Converting .PLY Frames to Animated Point Cloud .bin, don't find the scene file to display the animated point cloud.

### ISSUE THREAD

**Issue by HuangTianqi** [unitycoder/UnityPointCloudViewer#141]
I followed the tutorial (https://github.com/unitycoder/UnityPointCloudViewer/wiki/Converting-.PLY-Frames-to-Animated-Point-Cloud-.bin#viewing-generated-bin-file) to generate dynamic point clouds. But I can't find the scene file to display the dynamic point cloud. My plugin version is 2.7. I found that Sample-AnimatedPointCloudPlayer can display dynamic point clouds exported by Brekel. But I can't use the dynamic point cloud generated by the tutorial. I tested Brekel PointCloud 3 Trial x64, but the software seems to only support a few depth cameras. Is it possible to combine multiple frame point clouds(.ply) into one dynamic point cloud file with Brekel? Or is there any other way to support the display of dynamic point clouds generated from multiple PLY point cloud files?

**Comment by HuangTianqi** [comment]
Thank you for your quick reply. I tried to display the dynamic point cloud using the Sample-AnimatedPointCloudPlayer scene. The example given was runnable. Then I used the tool in the tutorial to generate the dynamic point cloud (https://github.com/unitycoder/UnityPointCloudViewer/wiki/Converting-.PLY-Frames-to-Animated-Point-Cloud-.bin# viewing-generated-bin-file), the generated point cloud reports an error when displaying it in the scene. See the image below. Now I have a few frames of point clouds (.ply), how can I composite the dynamic point clouds to display in the Sample-AnimatedPointCloudPlayer scene?
![UnityError](https://github.com/unitycoder/UnityPointCloudViewer/assets/12390596/eec79a61-187f-4d0c-ba31-1ca6b4fe25be)

**Comment by unitycoder** [comment]
if you can test whether [x] use array padding enabled or disabled makes any difference?

or if you disable [x] use large file streaming from the brekel viewer?

somehow the "starting large file streaming" displays, "118", it seems quite small?
