### ISSUE TITLE
Cannot divide by zero exception

### ISSUE THREAD

**Issue by DriesVRBase** [unitycoder/UnityPointCloudViewer#149]
Hi,

In the PointCloudViewerTilesDX11.cs script I sometimes had a 'cannot divide by zero' exception on the line:
`int stepCount = pointCount / stepSize;` 

You have this line in place as a safety
`int stepSize = pointCount / (gpuUploadSteps == 0 ? 1 : gpuUploadSteps);`. But if pointcount is smaller or equal to GpuUploadSteps it was still possible for stepsize to be zero. And in that case the pointcloud seems to stop with updating the tiles.

I changed the latter line to this:
`int stepSize = Math.Max(1, pointCount / (gpuUploadSteps == 0 ? 1 : gpuUploadSteps));`
And now it never happens anymore.

Might be worth implementing in the next release, thanks!

**Comment by unitycoder** [comment]
thanks, Added and will be available in next update!
