### ISSUE TITLE
Converting Brekel bpc to bin seems to have a binary version discrepancy I can't address

### ISSUE THREAD

**Issue by thePostFuturist** [unitycoder/UnityPointCloudViewer#39]
The documentation states 

2 = custom animated Brekel binary frames data *rest of the binary format is different for this data 

error:
`For Animated point cloud, file binaryVersion should have value (2) or bigger. received=66`

How do I convert the .bpc to .bin type 2? 

The point cloud to binary converter doesn't have an option in the dropdown for bpc, and the mesh converter gave me 4 empty chunks with error:

`Screen position out of view frustum (screen pos 256.000000, 0.000000, 93806903296.000000) (Camera rect 0 0 256 256)`

What's the process of conversion if I'm not following correct procedure? Or is this a bug? The documentation is a little vague.

**Comment by unitycoder** [comment]
you can only import the .bin output from brekel, not the actual brekel native files.
so inside brekel you export with this plugin format, from here
![image](https://user-images.githubusercontent.com/5438317/34473282-c2de98be-efab-11e7-9d3b-c2641f6ca555.png)

**Comment by thePostFuturist** [comment]
Is this only in Brekel's Point Cloud v2? Not seeing the File tab in Pro Body v2

**Comment by unitycoder** [comment]
yes, most likely then..
are there any middle formats that you could use between pro body in to brekel point cloud?
or what formats pro body exports?

**Comment by thePostFuturist** [comment]
.bpc ( Brekel point cloud ) is the closest match. I tweeted at him to this issue, maybe he can provide a converter.

**Comment by unitycoder** [comment]
thanks, let me know then.
What kind of data you are actually wanting to export & view in unity?

**Comment by thePostFuturist** [comment]
Sure thing.

I'd like to film an actor in point cloud and place her in a point cloud environment.

We're currently greenscreen chroma'ing her in the environment as a billboard, but a point cloud instead would be sweet.

**Comment by unitycoder** [comment]
is using pro body different from recording in that brekel pc?

currently one issue with my plugin is that the file format is quite bloated, and gets loaded into memory completely, compared to streaming from disk.. If you happen to have some sample recordings later, i could test with those files to add file streaming or more optimized file format.

**Comment by Brekel** [comment]
Indeed you can record pointclouds from Brekel Body v2 using the BPC (Brekel Point Cloud) file format which is optimized for efficiency.

Brekel PointCloud v2 is needed to export these to formats that 3D apps can handle.

You can also use Body & Pointcloud v2 simultaneously using the "Remote Triggering" functionality to have some more recording options.

**Comment by thePostFuturist** [comment]
Thanks -- does point cloud v2 convert .bpc I've recorded in body, or do you have to record in it initially?

**Comment by Brekel** [comment]
Yes BPC files recorded in Body v2 are meant for use in Pointcloud v2 and are the same as if they were recorded in Pointcloud.

**Comment by thePostFuturist** [comment]
Thanks!
