### ISSUE TITLE
add runtimeviewer caching option

### ISSUE THREAD

**Issue by unitycoder** [unitycoder/UnityPointCloudViewer#51]
so after you have parsed the file once, it could save it into .bin file for faster reading next time.
(if [x] save cache is enabled)

*or basically just allow the converter to be run at runtime, to make .bin files.

**Comment by IsDon** [comment]
Could we have any pointcloud saved with randomise points option into a new binary file [Editor]? Randomise on load is a slowdown that seems unnecessary.

**Comment by unitycoder** [comment]
next version has caching (resave) option for binaryviewer also (to save randomized cloud),
until have converter version that supports randomizing.

**Comment by unitycoder** [comment]
binary v2 and v3 formats support randomizing from converter, and there was caching option added for viewers.
