### ISSUE TITLE
Mesh Converter Point Size Material doesn't seem to be working 

### ISSUE THREAD

**Issue by CGCorps** [unitycoder/UnityPointCloudViewer#6]
Hi
I'm using the latest version of unity, I cant seem to get the pointsize material to work, nothing seems to happen when I move the slider.

**Comment by unitycoder** [comment]
Hi, if you are in dx11 mode, then the default mesh shader wont work, but works in dx9.

youll need to use the those pointmeshsizeDX11Quad or Tri ones, there is link to get the latest versions in docs or in shader folder.

**Comment by CGCorps** [comment]
cool thanx

**Comment by unitycoder** [comment]
closing this - and will update documentation for this soon.

**Comment by Sheppard27** [comment]
Hi,
Thanks for your work, I'm having trouble locating the 'pointmeshsizeDX11Quad' or 'Tri' shaders/material options. Could you possibly shed some light on where they might be found? 
Cheers
