### ISSUE TITLE
can this tool generate map from .pcd file ??

### ISSUE THREAD

**Issue by thienVTI** [unitycoder/UnityPointCloudViewer#71]
can this tool generate map from .pcd file ??

**Comment by unitycoder** [comment]
you can convert pcd(ascii), into point mesh.. but not sure if its useful as a game map?

what kind of map you want to have?

**Comment by thienVTI** [comment]
ok, thanks. I think that's helpful

**Comment by thienVTI** [comment]
can you build windows demo, so I can try ??

**Comment by unitycoder** [comment]
no demos available at the moment..
someone used pointcloud meshes like this, so it can look similar to that:
https://forum.unity.com/threads/released-point-cloud-viewer-tools.240536/page-7#post-3484775

with the new v3 tiles viewer, can have bigger clouds, where it culls them when out of view:
https://forum.unity.com/threads/released-point-cloud-viewer-tools.240536/page-8#post-5069648

**Comment by unitycoder** [comment]
closing
