### ISSUE TITLE
BinaryLoaderV2 2018.4.19f1

### ISSUE THREAD

**Issue by KodoMeiSpectre** [unitycoder/UnityPointCloudViewer#81]
Ive made good use of the BinaryLoaderV2 in Unity 2017.4.28f1 with no problems at all.
Right now im required to use it in 2018.4.19f1 which works fine till the point of hitting play and actually visualizing the cloud.
Problem is it does not appear at all, even though im getting the proper console outputs. 
Any idea why that could be?

**Comment by unitycoder** [comment]
does the sample file work? if you try to load: "PointCloudViewerSampleData\sample2.ucpc"

**Comment by KodoMeiSpectre** [comment]
Sample2.ucpc does work. Note that the file which is causing problems did work in 2017.x flawlessly. Initial Filetype before convert to binary is .pts.

**Comment by unitycoder** [comment]
is possible, email me the output and/or input pts file for testing.

also if you re-convert it, does it then work?

**Comment by unitycoder** [comment]
closing
