### ISSUE TITLE
Using multiple GPUs

### ISSUE THREAD

**Issue by Mitko88** [unitycoder/UnityPointCloudViewer#85]
Is it possible to use multiple GPUs for rendering? Currently, only one 1 can be used.

**Comment by unitycoder** [comment]
> Is it possible to use multiple GPUs for rendering? Currently, only one 1 can be used.

using built in unity rendering, and they dont seem to support multi-gpu stuff really..
they have some info here,
https://support.unity3d.com/hc/en-us/articles/211505603-How-well-Unity-does-scale-with-SLI-

**Comment by unitycoder** [comment]
closing - cannot really affect this, using unity features..
