### ISSUE TITLE
version 2.40 GetSubArray() error

### ISSUE THREAD

**Issue by MBrandt-NASA** [unitycoder/UnityPointCloudViewer#88]
Hi,

I just downloaded the latest version (2.40) into a clean Unity project using 2019.1.2f1 and currently see this error after importing the asset:

Assets\PointCloudTools\PointCloudViewerDX11\Scripts\PointCloudViewerTilesDX11.cs(1347,61): error CS1061: 'NativeArray<byte>' does not contain a definition for 'GetSubArray' and no accessible extension method 'GetSubArray' accepting a first argument of type 'NativeArray<byte>' could be found (are you missing a using directive or an assembly reference?)

The code where the error occurs is here:

`#if UNITY_2019_1_OR_NEWER
                        if (useNativeArrays == true)
                        {
                            point.x = tiles[i].pointsNative.GetSubArray(k * 3 * 4, 4).Reinterpret<float>(1)[0];
                            point.y = tiles[i].pointsNative.GetSubArray(k * 3 * 4 + 4, 4).Reinterpret<float>(1)[0];
                            point.z = tiles[i].pointsNative.GetSubArray(k * 3 * 4 + 4 + 4, 4).Reinterpret<float>(1)[0];
                        }`

Any ideas?  :)

Thanks

**Comment by Rickmc3280** [comment]
Did you go to edit project settings, player, other settings, "Allow unsafe code" (enabled)?  Also API compatability level .net 4.x?

**Comment by unitycoder** [comment]
ok, looks like its only available in 2019.3 and later..

need to change this
`#if UNITY_2019_1_OR_NEWER
`
into
`#if UNITY_2019_3_OR_NEWER`

which will then break point picking in v3 viewer, for 2019.2 and lower versions.
I'll check for some alternatives there.

![image](https://user-images.githubusercontent.com/5438317/96830203-b4959b80-1443-11eb-9b28-9ca73775da6e.png)

**Comment by unitycoder** [comment]
update is now live https://assetstore.unity.com/packages/tools/utilities/point-cloud-viewer-and-tools-16019?aid=1101lGti
