### ISSUE TITLE
PointCloud Mesh Rendering

### ISSUE THREAD

**Issue by vonengel3d** [unitycoder/UnityPointCloudViewer#99]
I'm having a very large point cloud (>300mio points) which I'm trying to render in your v3 format. I'm facing issues with the drawproceduralnow rendering since it does not honor the unity rendering queue system. Therefore I tried enabling the experimental mesh rendering. I noticed that the updating of the meshes per tile is commented for unity >2019.1. Is this by accident or is this feature not fully implemented?
Do you have a new version that supports mesh based rendering of tiles?

**Comment by unitycoder** [comment]
yes, v3 mesh rendering should had been hidden/disabled.. its not complete (colors are not supported, and few other things are still broken).

rendering queue issue:
yes thats still issue with v3, happens with transparent objects, so the current workaround is to not use transparent material (which i know its not easy..) info https://github.com/unitycoder/UnityPointCloudViewer/issues/77

the real fix will be when i get to add commandbuffer rendering to V3 (like its supported in v1/v2 viewer)

**Comment by unitycoder** [comment]
v3 mesh rendering not yet available, so closing this old issue
